"""separated due date and time

Revision ID: c69bb1008894
Revises: ce27229ca595
Create Date: 2024-10-26 12:46:31.121400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69bb1008894'
down_revision = 'ce27229ca595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('due_time', sa.Time(), nullable=True))
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DATETIME(), nullable=True))
        batch_op.drop_column('due_time')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
