"""made due date required

Revision ID: dc2f6853b299
Revises: c69bb1008894
Create Date: 2024-10-26 12:54:41.961662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2f6853b299'
down_revision = 'c69bb1008894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_index('ix_assessment_module')
        batch_op.drop_index('ix_assessment_title')
        batch_op.create_index(batch_op.f('ix_assessment_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_due_date'))
        batch_op.drop_index(batch_op.f('ix_assessment_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_assessment_completed_at'))
        batch_op.create_index('ix_assessment_title', ['title'], unique=False)
        batch_op.create_index('ix_assessment_module', ['module'], unique=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
