"""changed title limit to 50 chars

Revision ID: dd2ea13bdae6
Revises: dc2f6853b299
Create Date: 2024-10-30 20:31:59.265320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2ea13bdae6'
down_revision = 'dc2f6853b299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_assessment')
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_index('ix_assessment_module')
        batch_op.drop_index('ix_assessment_title')
        batch_op.create_index(batch_op.f('ix_assessment_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_due_date'))
        batch_op.drop_index(batch_op.f('ix_assessment_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_assessment_completed_at'))
        batch_op.create_index('ix_assessment_title', ['title'], unique=False)
        batch_op.create_index('ix_assessment_module', ['module'], unique=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('_alembic_tmp_assessment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('module', sa.VARCHAR(length=10), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('desc', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('modified_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('due_time', sa.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
